services:
  postgres:
    image: postgres:13
    command: ['postgres', '-c', 'log_statement=all']
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    restart: unless-stopped
