apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: meteorology-minimizer
spec:
  jobTargetRef:
    activeDeadlineSeconds: 3600
    backoffLimit: 1
    template:
      spec:
        containers:
          - name: main
            image: '{{ .Values.image }}:{{ .Values.imageTag }}'
            command: ['stiltctl', 'minimize-meteorology']
            envFrom:
              - configMapRef:
                  name: environment
              - secretRef:
                  name: db-secret
            resources:
              requests:
                cpu: 200m
                memory: 1000Mi
              limits:
                cpu: 1000m
                memory: 2000Mi
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 10
  maxReplicaCount: 10
  triggers:
    - type: postgresql
      metadata:
        connectionFromEnv: POSTGRES_CONNECTION
        query: "SELECT COUNT(*) FROM events WHERE event_name = 'stiltctl.events.SceneCreated'"
        targetQueryValue: '1'
